### PR TITLE
Add debug build support

### PR DESCRIPTION
**Pull request by Kudo**
To troubleshoot crash issue easier, this PR adds debug build support.
Uncommenting `export BUILD_TYPE=Debug` in scripts/start.sh to enable debug build.
In debug build, it will use full symbol mode (-g2) and debug symbol will be bundled in libjsc.so (turn off DEBUG_FISSION).

This PR includes many changes, will go though here.
1. Update patch files exactly to prevent fuzzing patch after upgrade to WebKitGTK 2.22.6.

2. [patches/jsc.patch] Remove [first patch of FindICU.cmake](https://github.com/react-native-community/jsc-android-buildscripts/blob/master/patches/jsc.patch#L44-L73) that will be overwritten by [second patch](https://github.com/react-native-community/jsc-android-buildscripts/blob/master/patches/jsc.patch#L208-L259) actually.

3. Control JSC options by supported cmake options instead of patching.
```diff
-+set(ENABLE_SAMPLING_PROFILER OFF)
-+set(ENABLE_DFG_JIT ON)
-+set(ENABLE_FTL_JIT OFF)
-+set(ENABLE_JIT ON)
```
```diff
+  -DENABLE_SAMPLING_PROFILER=OFF \
+  -DENABLE_JIT=ON \
+  -DENABLE_DFG_JIT=ON \
+  -DENABLE_FTL_JIT=OFF \
```

4. Disable RTTI and exception support. JSC cmake will disable these and ICU does not need these.

5. JSC cmake default option will use gold LD, we don't need these. Leaving gold LD only for ICU.

6. Remove JSC c++11 compile option, JSC cmake option will override this by c++14.

7. Do not strip symbol during AAR packaging. Gradle will do this during APK packaging.

### CODE REVIEW

**Comment by Kudo** [comment]
BTW, CI is passed by my CircleCI fork.
https://circleci.com/gh/Kudo/jsc-android-buildscripts/7

**Comment by Kudo** [comment]
Close this first and will re-send a PR after #103 merged. That would be clear where I patched for debug build support.

**Comment by chufengma** [comment]
image

debug jsc size : 300M ...

how can i get small jsc.so with symbols?

**Comment by Kudo** [comment]
@chufengma debug build is only for troubleshooting during development.
E.g. To set breakpoints and check memory footprint for each variables.

If you only need crash backtrace, the release build is enough.

**Comment by chufengma** [comment]
@Kudo I misunderstood before.Thank you very much! 

add this to not strip libjsc symbols:
```
packagingOptions {
        doNotStrip "*/libjsc.so"
}
```

**Pull request closed without merging**
