### PR TITLE
Disable the Debug Heap In All Cases

### PR DESCRIPTION
**Pull request by webghost009**
This patch disables the JSC debug heap in all cases.

posix_memalign gets patched out which causes DebugHeap::memalign to crash. This isn't usually a problem since the DebugHeap isn't used. However, it can be activated by loading the ASAN or TSAN libraries. In my experience, this causes JSC to crash soon after. This makes it impossible to use these types of tools to debug your own C++ code running alongside JSC.

## Test Plan

Ran the modified build of JSC on an x86 simulator and a real Pixel 2 (armeabi-v7a) with and without ASAN enabled in my own C++ code. Observed that JSC did not crash in any of these cases.

### What's required for testing (prerequisites)?
A local build of JSC with the included modifications and a RN project modified to to use the wrap.sh feature to LD_PRELOAD the ASAN library. 

https://developer.android.com/ndk/guides/wrap-script
https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid

### What are the steps to reproduce (after prerequisites)?
Run the application using a publicly released build of jsc-android on a device with the appropriate wrap.sh and ASAN .so included and observe the crash. Then switch to use the local JSC build with this patch and observe that it does not crash.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by webghost009** [comment]
Is there anything I can do to help get this committed?

Here's a bit more explanation in case it helps.

Because Android API version 16 doesn't include posix_memalign(), the call to it gets patched out to work around the compilation error it causes. This is done by jsc_fix_build_error_memalign.patch. DebugHeap::memalign() becomes:
```C++
void* DebugHeap::memalign(size_t alignment, size_t size, bool crashOnFailure)
{
    BCRASH();
    return nullptr;
}
```
The DebugHeap isn't typically enabled. But it can be. The decision is made by Environment::computeIsDebugHeapEnabled():
```C++
bool Environment::computeIsDebugHeapEnabled()
{
    if (isMallocEnvironmentVariableSet())
        return true;
    if (isLibgmallocEnabled())
        return true;
    if (isSanitizerEnabled())
        return true;
#if BUSE(CHECK_NANO_MALLOC)
    if (!isNanoMallocEnabled() && !shouldProcessUnconditionallyUseBmalloc())
        return true;
#endif
    return false;
}
```

isSanitizerEnabled() is the particular check giving me problems (though the other checks may also be of concern in other scenarios). This method searches the current process for the ASAN and TSAN init methods:
```C++
static bool isSanitizerEnabled()
{
    void* handle = dlopen(nullptr, RTLD_NOW);
    if (!handle)
        return false;
    bool result = !!dlsym(handle, "__asan_init") || !!dlsym(handle, "__tsan_init");
    dlclose(handle);
    return result;
}
```

The decision made by Environment::computeIsDebugHeapEnabled() is cached by the Environment object and exposed outward via Environment::isDebugHeapEnabled(). This method is then referenced in several places by Webkit's custom allocator, bmalloc. Here it's used in the bmalloc Heap constructor to decide whether to allocate a DebugHeap object:
```C++
Heap::Heap(HeapKind kind, std::lock_guard<Mutex>&)
    : m_kind(kind)
    , m_vmPageSizePhysical(vmPageSizePhysical())
    , m_debugHeap(nullptr)
{
    RELEASE_BASSERT(vmPageSizePhysical() >= smallPageSize);
    RELEASE_BASSERT(vmPageSize() >= vmPageSizePhysical());

    initializeLineMetadata();
    initializePageMetadata();
    
    if (PerProcess<Environment>::get()->isDebugHeapEnabled())
        m_debugHeap = PerProcess<DebugHeap>::get();
    else {
        Gigacage::ensureGigacage();
#if GIGACAGE_ENABLED
        if (usingGigacage()) {
            RELEASE_BASSERT(gigacageBasePtr());
            m_largeFree.add(LargeRange(gigacageBasePtr(), gigacageSize(), 0, 0));
        }
#endif
    }
    
    m_scavenger = PerProcess<Scavenger>::get();
}
```

When the ASAN wrap.sh, included with the Android NDK, is used:
```
#!/system/bin/sh
HERE="$(cd "$(dirname "$0")" && pwd)"
export ASAN_OPTIONS=log_to_syslog=false,allow_user_segv_handler=1
export LD_PRELOAD=$HERE/libclang_rt.asan-arm-android.so
"$@"
```
libclang_rt.asan-arm-android.so is loaded before JSC and so the symbol __asan_init exists when the sanitizer check is performed. The decision to enable the debug heap is made and JSC crashes with a SIGILL when DebugHeap::memalign() is called and invokes BCRASH().

This patch avoids the crash by modifying Environment::computeIsDebugHeapEnabled() to always return false so that the DebugHeap is never used and the method causing the crash is never called.

**Comment by Kudo** [comment]
@webghost009 Thanks for your contribution and brief explanation.
I was revisiting the patch of posix_memalign and found that there is an implementation in ndk support library.
https://android.googlesource.com/platform/ndk/+/master/sources/android/support/src/posix_memalign.cpp
Do you think if it is possible to patch and support posix_memalign()?
Assuming this would help for DebugHeap works as expectation for ASAN mode.

**Comment by webghost009** [comment]
Hi @Kudo! Thanks for getting back to me.

I'm not yet familiar with all of the intricacies of the Android NDK ecosystem. Is it safe to directly link to libandroid_support? Is that what you're suggesting? [Reading a bit about the library](https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html), it seems it may only be intended to be linked into libc++?

Regardless, I have confirmed that posix_memalign exists in r17c's libandroid_support.a:
```
~/jsc-android-buildscripts$ nm ~/ndk/android-ndk-r17c/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libandroid_support.a | grep align
posix_memalign.o:
         U memalign
00000001 T posix_memalign
```

It seems you've referenced [this bug](https://github.com/android-ndk/ndk/issues/647) before, where posix_memalign() was changed to be >= API 17. Was this change a mistake? Should it be supported in older API levels by virtue of the support library?

For my use case, I don't yet see an advantage to enabling the DebugHeap in JSC when ASAN is used. As I understand things (please correct me if I'm wrong here), JSC must communicate with my C++ code via JSC->Bridge->Java->JNI->C++ which cannot pass memory pointers. Therefore, having JSC use the standard allocation routines, rather than its custom heap, wouldn't help ASAN identify problems in my own C++ code. However, I could see the DebugHeap being useful for android-jsc developers trying to track down problems within JSC itself.

Please let me know how you would like to proceed. I'm all for maintaining the DebugHeap functionality if it can be done in a supportable way.

Thanks!

**Comment by webghost009** [comment]
Hello @Kudo. Have you had a chance to think about this?

**Comment by Kudo** [comment]
@webghost009 Sorry for late and making you confused for NDK support lib.
The point is to add some polyfiil like stuff to support posix_memalign.
Somehow like what we did for log2.
https://github.com/react-native-community/jsc-android-buildscripts/blob/master/patches/jsc_fix_build_error_log2.patch

The posix_memalign implementation could get from NDK support lib as the link I posted before.
This advantage of this polyfill is that we don't change JavaScriptCore's behavior but to make it supported at Android.

**Comment by webghost009** [comment]
@Kudo - I've implemented a fix as you've suggested. I've made another pull request. Please see https://github.com/react-native-community/jsc-android-buildscripts/pull/109

**Pull request closed without merging**
