### PR TITLE
Upgrade ICU

### LINKED ISSUE #98: Intl version missing country locale
### Issue Description

Locale English (Germany)

```
date.toLocaleString('en-DE', {year: 'numeric', month: 'numeric', day: 'numeric'})
```

returns 

```
12/20/2012
```

but should return

```
20.12.2012
```

Locale German (United States)

```
date.toLocaleString('de-US', {year: 'numeric', month: 'numeric', day: 'numeric'})
```

returns 

```
20.12.2012
```

but should return

```
12/20/2012
```

It seems like whatever country is specified in the locale it is just being ignored.

### Version, config, any additional info

```
"jsc-android": "236355.1.1"
```
using intl via
```
implementation "org.webkit:android-jsc-intl:r236355"
```

### PR DESCRIPTION
**Pull request by Kudo**
# Summary
    Upgrade ICU to Chromium M76 used version. Fixes #98 
    ICU version is 64.2

    https://chromium.googlesource.com/chromium/src/+/refs/tags/76.0.3809.87/DEPS#984
    https://chromium.googlesource.com/chromium/deps/icu/+/64e5d7d43a1ff205e3787ab6150bbc1a1837332b%5E%21/

    Some changes are for ICU 64 data buildtool changes.
    https://github.com/unicode-org/icu/blob/master/docs/userguide/icu_data/buildtool.md

### What's required for testing (prerequisites)?
Use Intl version and verify the test case provided by @danilobuerger
Expected result should be:
```
var x = 1.2;
console.log(x.toLocaleString('de-US'));
console.log(x.toLocaleString('en-DE'));
> "1,2"
> "1,2"
```

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ❌     |
| Android |    ✅     |

## Checklist

- [x] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`

### CODE REVIEW

**Comment by danilobuerger** [comment]
@Kudo Thanks so much for this PR! I built a custom jsc with this patch applied and tested it. The locales are now working properly.

**Comment by danilobuerger** [comment]
@Kudo @kmagiera Any chance to get this merged and released?

**Comment by Kudo** [comment]
Rerun the CI task and it's green now.
I am going the merge this and thanks for @kmagiera's help to review.

**Comment by danilobuerger** [comment]
@Kudo @kmagiera could we please get a release with this?

**Pull request merged**
