### PR TITLE
Upgrade WebKitGTK+ to 2.22.6

### LINKED ISSUE #85: Upgrade JSC version
### Issue Description
Just seen https://webkitgtk.org/security/WSA-2018-0009.html that current WebKitGTK+ version has vulnerability issues.
However, the CVEs are kept secretly right now, I am not sure if these vulnerabilities are in JSC or maybe just in WebCore.
Do you have plans to upgrade WebKitGTK+ to 2.22.6?

### PR DESCRIPTION
**Pull request by Kudo**
Closes #85 
For security vulnerabilities: https://webkitgtk.org/security/WSA-2018-0009.html

Tested on my arm device with RNTester okay.
I don't have a Pixel phone and cannot update measurement result as these result are from Pixel phone.

### CODE REVIEW

**Comment by rotemmiz** [comment]
Hey @kmagiera, is there something holding back the release of 241213.x.x ? I really want to test if the issue reported in https://github.com/react-native-community/jsc-android-buildscripts/issues/84 is resolved.

**Comment by kmagiera** [comment]
Hi @rotemmiz – no there is nothing really. I just haven't had a chance to try that version by myself. I can publish it on npm with "beta" tag and would appreciate if you could verify if it work for you

**Comment by kmagiera** [comment]
image

Just published 241213.0.0 tagged as "canary" would appreciate any comments if you get a chance to try it.

**Comment by rotemmiz** [comment]
Unfortunately, the same crash persists on 241213 :(

**Pull request merged**
