### PR TITLE
Disable DFG_JIT to fix possibly crash issue.

### PR DESCRIPTION
**Pull request by Kudo**
# Summary

Disable [DFG JIT](https://trac.webkit.org/wiki/JavaScriptCore#CoreEngine) in JavaScriptCore to fix crash issues.
As far as I know, there are two kinds of crash.
https://github.com/react-native-community/jsc-android-buildscripts/issues/84#issue-407898908
And
https://github.com/facebook/react-native/issues/24261#issuecomment-493245483
Both of them are caused from DFG JIT.
To prevent further crash issues, I am proposing to disable DFG.

Some notes:
old JSC [disabled DFG JIT](https://github.com/facebook/android-jsc/blob/master/jsc/BUCK#L1065)
jsc-android [disabled DFG_JIT until 236355.0.0](https://github.com/react-native-community/jsc-android-buildscripts/pull/65)

## Test Plans
1. As I could reproduced the first NPE crash, https://github.com/react-native-community/jsc-android-buildscripts/issues/84#issuecomment-474945947 confirmed to fix NPE with no_DFG_JIT build.
2. Also double confirmed previous crash on arm64 before WebKitGTK 2.22 does not happens
https://github.com/react-native-community/jsc-android-buildscripts/issues/84#issuecomment-475181051
3. For second crash issue, there are some user feedback that the no_DFG_JIT build fix their crash issues.
See detail comments in https://github.com/facebook/react-native/issues/24261

## Measurement
I am not going to compare with [original measurement result](https://github.com/react-native-community/jsc-android-buildscripts/blob/master/measure/README.md) since I don't have Pixel phone.
Instead to test on Samsung Galaxy Note5.
Four test runs: original 241213.1.0, old JSC, no_DFG_JIT, and no_JIT.
Note that I've updated [render deep scale](https://github.com/react-native-community/jsc-android-buildscripts/blob/master/measure/suites/RenderProfile.js#L10) to 500.
Otherwise, I will have JNI local reference table overflow crash (JNI maximum references is 512)

| Npm Version | Publish Date | Config | WebkitGTK Revision | WebkitGTK Date | TTI | SunSpider | Jetstream Hashmap | Octane2 | SixSpeed | Render Flat | Render Deep | Size |
| :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: | :---: |
| 241213.1.0 | 2019-04-30 | webkitGTK:2.22.6<br/>chromiumICUCommit:b34251f<br/>i18n:false<br/> | 241213 | 2019-02-08 | 456 | 469 | 557 | 1569 | 416 | 436 | 347 | 7.6/10.0 |
| 174650.0.2 | - | Stock RN59 (non-i18n) | 174650 | 2014-10-13 | 454 | 568 | 4005 | 1996 | 1454 | 518 | 395 | 2.7 (with libicu_common.so) |
| @kudo-ci/jsc-android@241213-no-dfg-jit | 2019-05-17 | webkitGTK:2.22.6<br/>chromiumICUCommit:b34251f<br/>i18n:false<br/>DFG_JIT:false<br/> | 241213 | 2018-09-21 | 451 | 534 | 3033 | 1780 | 420 | 510 | 430 | 6.3/8.0 |
| @kudo-ci/jsc-android@241213-no-jit | 2019-05-17 | webkitGTK:2.22.6<br/>chromiumICUCommit:b34251f<br/>i18n:false<br/>DFG_JIT:false<br/>JIT:false<br/> | 241213 | 2018-09-21 | 456 | 1947 | 11799 | 5887 | 973 | 538 | 431 | 5.0/7.1 | 

I prepared a graph to show the result visually.
https://docs.google.com/spreadsheets/d/1hqX3ai-NCpN_J6YQDTKnKNBctWnMFA6EyOdVhPvwUas/edit#gid=445596593
Screen Shot 2019-05-23 at 6 50 52 PM

From the graph, you could see there's no much benefits from DFG JIT except the jetstream hash-map test case.
And disable DFG JIT also save about 1.3MB for libjsc.so (about 17%)
From my point of view, to disable DFG JIT we keep the performance baseline as old JSC.
However, bug free and small binary size are more meaningful to me.

### CODE REVIEW

**Comment by cpirich** [comment]
@kudo thanks for your work here, we've also been bitten by SEGV_MAPPER crashes and corruption within the JavaScript side. We will try this out.

A point of clarification: in your chart above, you mention "Stock RN59" using 174650.0.2, but perhaps you mean "Stock RN58"? I think RN59 by default is now using `236355`

**Comment by ItsNoHax** [comment]
Have you published it already @kmagiera ?

**Comment by Kudo** [comment]
Sorry it's me ask for pending new release for a while.
As there still some user report crash happens even after disable DFG JIT.
I would like to make sure we publish a new version that will truly solve the crash.

@cpirich Oops, it's my wrong for RN59. As you said, it's stock RN058. Thanks for clarification.

**Comment by ItsNoHax** [comment]
Understandable @Kudo , thanks again for all the effort you have been putting into fixing this asap.

**Pull request merged**
