### PR TITLE
Update for RN 0.60 

### PR DESCRIPTION
**Pull request by Kudo**
Newer RN manages JSC by node dependency.
https://github.com/facebook/react-native/pull/24276
Integrate and update JSC would be easier than before.

However, [in the PR comments](https://github.com/facebook/react-native/pull/24276) there are still some enhancements could be done.

1. Align NDK version to prevent potential ABI incompatible issue.
2. Remove libc++_shared.so from jsc-android.aar, so that user don't need to use `packagingOptions.pickFirst` to exclude them.
   For RN 0.58 and before, since it was built by gcc.
  These is no libc++_shared.so but libgnustl_shared.so.
  For jsc-android side, provide an android-jsc-cppruntime.aar for user to add libc++_shared.so.

### CODE REVIEW

**Comment by kmagiera** [comment]
Thanks @Kudo this looks good, the only question is if we really need that `.gitignore` there? If so I'd prefer to keep everything in top level gitignore. I believe most of the excludes are already there

**Comment by Kudo** [comment]
The .gitignore is not necessary and removed.
Please help to double check again.
Thank you.

**Comment by kmagiera** [comment]
Looks ok, will just wait for CI to finish and then merge

**Comment by Kudo** [comment]
CI weirdly kicked to my CI fork but is pass anyway.
https://circleci.com/gh/Kudo/jsc-android-buildscripts/8

**Pull request merged**
